[[main]]
  identifier = 'github'
  url    = 'https://github.com/alfaloo'
  weight     = 1
  name       = 'GitHub'
  pre        = 'github'

[[main]]
  identifier = 'linkedin'
  url    = 'https://linkedin.com/in/zhiyanglu'
  weight     = 2
  name        = 'LinkedIn'
  pre        = 'linkedin'

[[main]]
  identifier = 'x'
  url    = 'https://x.com/alfaloo528'
  weight     = 4
  name        = 'X.com'
  pre        = 'x'

[[footer]]
  identifier = 'github'
  url    = 'https://github.com/alfaloo'
  weight     = 1
  name       = 'GitHub'
  pre        = 'github'

[[footer]]
  identifier = 'linkedin'
  url    = 'https://linkedin.com/in/zhiyanglu'
  weight     = 2
  name        = 'LinkedIn'
  pre        = 'linkedin'

[[footer]]
  identifier = 'x'
  url    = 'https://x.com/alfaloo528'
  weight     = 4
  name        = 'X.com'
  pre        = 'x'